// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmfMOApMxZ0XMDLbUsun2rCTS9qgTaw30',
    appId: '1:158953742233:web:da9a15d944650d8b07fd08',
    messagingSenderId: '158953742233',
    projectId: 'todo-87ea5',
    authDomain: 'todo-87ea5.firebaseapp.com',
    storageBucket: 'todo-87ea5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAniIITusURXGaYk2kfzx6K4zBe4Q9g53I',
    appId: '1:158953742233:android:57ebbd19cda085ac07fd08',
    messagingSenderId: '158953742233',
    projectId: 'todo-87ea5',
    storageBucket: 'todo-87ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdn-FAd1OfIhS2i059KyuEUu7r1CPTnI',
    appId: '1:158953742233:ios:f676823ef2ff7a1a07fd08',
    messagingSenderId: '158953742233',
    projectId: 'todo-87ea5',
    storageBucket: 'todo-87ea5.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPdn-FAd1OfIhS2i059KyuEUu7r1CPTnI',
    appId: '1:158953742233:ios:fc1d82c1ca0a1f2207fd08',
    messagingSenderId: '158953742233',
    projectId: 'todo-87ea5',
    storageBucket: 'todo-87ea5.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
